language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "10"
git:
  depth: 3
script:
  - yarn build --prefix-paths
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GH_TOKEN
  local_dir: public
  target_branch: gh-pages
  on:
    branch: master
